services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - LOCAL=${LOCAL}
      - NODE_ENV=${NODE_ENV}
      - DECRYPTION_METHOD=${DECRYPTION_METHOD}
      - SITE_TOKEN=${SITE_TOKEN}
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - PRIVATE_KEY=${PRIVATE_KEY}
    command: npm start